// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPVZkBL-OAu_lRyCYTd3l6vQJMLR4XfpE',
    appId: '1:444185295327:web:5c99b8c6add18e13366c6a',
    messagingSenderId: '444185295327',
    projectId: 'medinas-app-5fe26',
    authDomain: 'medinas-app-5fe26.firebaseapp.com',
    storageBucket: 'medinas-app-5fe26.appspot.com',
    measurementId: 'G-CP7ZLWXVX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ktd-wnssZGv-SuwgOw0NEh1t6C9XDMM',
    appId: '1:444185295327:android:f6056600c642ed0f366c6a',
    messagingSenderId: '444185295327',
    projectId: 'medinas-app-5fe26',
    storageBucket: 'medinas-app-5fe26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2xZrvLza76tk9fETIkRwXyogtLf3CjEc',
    appId: '1:444185295327:ios:ef0716a90ba57eea366c6a',
    messagingSenderId: '444185295327',
    projectId: 'medinas-app-5fe26',
    storageBucket: 'medinas-app-5fe26.appspot.com',
    iosBundleId: 'com.example.medinasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2xZrvLza76tk9fETIkRwXyogtLf3CjEc',
    appId: '1:444185295327:ios:ef0716a90ba57eea366c6a',
    messagingSenderId: '444185295327',
    projectId: 'medinas-app-5fe26',
    storageBucket: 'medinas-app-5fe26.appspot.com',
    iosBundleId: 'com.example.medinasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPVZkBL-OAu_lRyCYTd3l6vQJMLR4XfpE',
    appId: '1:444185295327:web:f9f09a78a5010c8a366c6a',
    messagingSenderId: '444185295327',
    projectId: 'medinas-app-5fe26',
    authDomain: 'medinas-app-5fe26.firebaseapp.com',
    storageBucket: 'medinas-app-5fe26.appspot.com',
    measurementId: 'G-PJ7XJT2GLF',
  );
}
